from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from jarvis.planner.ai_plan_adapter import (
    AIPlanAdaptationResult,
)
from jarvis.planner.ai_plan_contract import (
    AIPlanDraft,
    AIPlanStepDraft,
)
from jarvis.planner.ai_plan_execution import (
    AIPlanExecutionResult,
)
from jarvis.planner.ai_plan_memory import (
    AIPlanMemoryRecord,
    AIPlanMemoryStore,
)
from jarvis.planner.ai_plan_pipeline import (
    AIPlanPipelineResult,
)
from jarvis.planner.ai_plan_reflection import (
    AIPlanReflectionResult,
    AIPlanReflectionService,
)
from jarvis.planner.ai_plan_validation import (
    AIPlanValidationResult,
)
from jarvis.planner.executor import PlanExecutionResult
from jarvis.planner.orchestrator import (
    PlannerOrchestrator,
    PlanPreview,
)


class AIAgentRunStatus(StrEnum):
    NO_PLAN = "no_plan"
    CONFIRMATION_REQUIRED = "confirmation_required"
    COMPLETED = "completed"


@dataclass(slots=True, frozen=True)
class AIAgentRunResult:
    status: AIAgentRunStatus
    preview: PlanPreview | None
    execution: PlanExecutionResult | None
    reflection: AIPlanReflectionResult | None
    memory_record: AIPlanMemoryRecord | None

    @property
    def requires_confirmation(self) -> bool:
        return (
            self.status
            is AIAgentRunStatus.CONFIRMATION_REQUIRED
        )

    @property
    def success(self) -> bool:
        return (
            self.execution is not None
            and self.execution.success
        )


class AIAgentRuntime:
    def __init__(
        self,
        *,
        orchestrator: PlannerOrchestrator,
        reflection: AIPlanReflectionService,
        memory: AIPlanMemoryStore,
    ) -> None:
        self._orchestrator = orchestrator
        self._reflection = reflection
        self._memory = memory

    async def run(
        self,
        text: str,
    ) -> AIAgentRunResult:
        preview = await self._orchestrator.prepare(
            text
        )

        if preview is None:
            return AIAgentRunResult(
                status=AIAgentRunStatus.NO_PLAN,
                preview=None,
                execution=None,
                reflection=None,
                memory_record=None,
            )

        if preview.requires_confirmation:
            return AIAgentRunResult(
                status=(
                    AIAgentRunStatus.CONFIRMATION_REQUIRED
                ),
                preview=preview,
                execution=None,
                reflection=None,
                memory_record=None,
            )

        execution = await self._orchestrator.execute_preview(
            preview
        )

        wrapped_execution = self._wrap_execution(
            execution
        )

        reflection = self._reflection.reflect(
            wrapped_execution
        )

        memory_record = self._memory.remember(
            execution=wrapped_execution,
            reflection=reflection,
            metadata={
                "source": "ai_agent_runtime",
            },
        )

        return AIAgentRunResult(
            status=AIAgentRunStatus.COMPLETED,
            preview=preview,
            execution=execution,
            reflection=reflection,
            memory_record=memory_record,
        )

    async def confirm_pending(
        self,
    ) -> AIAgentRunResult:
        execution = await self._orchestrator.confirm_pending()

        wrapped_execution = self._wrap_execution(
            execution
        )

        reflection = self._reflection.reflect(
            wrapped_execution
        )

        memory_record = self._memory.remember(
            execution=wrapped_execution,
            reflection=reflection,
            metadata={
                "source": "ai_agent_runtime_confirmed",
            },
        )

        return AIAgentRunResult(
            status=AIAgentRunStatus.COMPLETED,
            preview=None,
            execution=execution,
            reflection=reflection,
            memory_record=memory_record,
        )

    def cancel_pending(
        self,
    ) -> bool:
        return self._orchestrator.cancel_pending()

    @staticmethod
    def _wrap_execution(
        execution: PlanExecutionResult,
    ) -> AIPlanExecutionResult:
        plan = execution.plan

        draft = AIPlanDraft(
            goal=plan.goal,
            steps=tuple(
                AIPlanStepDraft(
                    capability=step.capability,
                    arguments=dict(
                        step.arguments
                    ),
                    description=step.description,
                )
                for step in plan.steps
            ),
            reasoning_summary=(
                "Generated by the existing JarvisAI "
                "AIPlanGenerator and PlannerOrchestrator."
            ),
        )

        validation = AIPlanValidationResult(
            valid=True,
            issues=(),
        )

        adaptation = AIPlanAdaptationResult(
            plan=plan,
            validation=validation,
        )

        pipeline = AIPlanPipelineResult(
            draft=draft,
            adaptation=adaptation,
        )

        return AIPlanExecutionResult(
            pipeline=pipeline,
            execution=execution,
        )
